# Generated by Django 5.2.8 on 2025-12-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Adminsttartor'), ('librarian', 'stocks books'), ('member', 'Member')], max_length=20),
        ),
    ]
